### STAGE 1: Build ###
FROM node:14 AS build
WORKDIR /usr/src/app
COPY package.json .
RUN npm install
COPY . .
RUN npm run build
### STAGE 2: Run ###
FROM nginx:1.17.1-alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /usr/src/app/dist/supplement /usr/share/nginx/html

# FROM node:14

# WORKDIR /angular-app

# COPY package.json .

# RUN npm install

# COPY . .

# RUN npm run build

# # Expose the port the app runs on
# EXPOSE 58123

# # Define the command to start the app
# CMD ["npm", "start"]